apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: pipeline-build-git-run
spec:
  pipelineRef:
    name: pipeline-build-git
  serviceAccounts:
    - taskName: build-git
      serviceAccount: reversewords-pipeline
  
