apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  annotations:
  labels:
    tekton.dev/pipeline: build-git
  name: build-git-run-gcskd
spec:
  params:
    - name: GIT_REPOSITORY
      value: github.com/ch-stark/tutorial-tekton-argocd-infra
    - name: GIT_MANIFEST_DIR
      value: yamls/ocp
    - name: GIT_EMAIL
      value: cstark@redhat.com
    - name: GIT_NAME
      value: forked from Carlos Santana
    pipelineRef:
      name: build-git
    serviceAccountName: pipeline-service-account  
    podTemplate: {}
    resources:
    - name: source
      resourceRef:
        name: source
    - name: image
      resourceRef:
        name: image
  
  
  

